### ISSUE TITLE
Do we need "testable"?

### ISSUE THREAD

**Issue by jeremiak** [18F/about_yml#11]
Per @gboone's points today on the call, should we remove the `testable` key? I think, at least as far as 18F is concerned, that a `.travis.yml` search might be better proxy for this than an arbitrary key that might not be updated?

**Comment by arowla** [comment]
Not all projects may be hooked up to CI, yet still have tests (or not have
tests but potentially could). This flag was to control for that.

On Fri, Oct 9, 2015 at 12:16 PM, Jeremia Kimelman notifications@github.com
wrote:

> Per @gboone https://github.com/gboone's points today on the call,
> should we remove the testable key? I think, at least as far as 18F is
> concerned, that a .travis.yml search might be better proxy for this than
> an arbitrary key that might not be updated?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/about_yml/issues/11.

## 

Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by mbland** [comment]
Right, so we (being the [Testing Grouplet](https://github.com/18F/wg-testing/), instigators of the `.about.yml`/Team API) could find out what projects _should_ have CI, and follow up to help get them set up. Or to see what builds are often broken, and either help fix them for the "testable" projects, or help tear down busted old repos, or at least shut off their builds.

**Comment by jeremiak** [comment]
Awesome, understood. Let's keep it in there then!
