### ISSUE TITLE
`status` is required, but is not part of the generated template

### ISSUE THREAD

**Issue by arowla** [18F/about_yml#21]
Running `about_yml_generate` should produce all required fields.

(And it could be that status simply shouldn't be required anymore.)

**Comment by mbland** [comment]
Yeah, `status` got yanked in #18.

**Comment by arowla** [comment]
Hey @mbland , is there a PR or other issue to fix the bug where `status` is still a required field?

**Comment by mbland** [comment]
Did you update the gem to v0.0.4? It shouldn't still be required.

**Comment by monfresh** [comment]
I was under the impression that `status` _should_ be required. In the project dashboard, I'm only pulling in repos that have an `active` status.

**Comment by arowla** [comment]
I think the concept of active and non-active has been subsumed by the
various (non-binary) values in `stage`. For instance, `stage: sunset` would
be considered non-active.

On Tue, Oct 27, 2015 at 12:34 PM, Moncef Belyamani <notifications@github.com

> wrote:
> 
> I was under the impression that status _should_ be required. In the
> project dashboard, I'm only pulling in repos that have an active status.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/about_yml/issues/21#issuecomment-151561183.

## 

Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by monfresh** [comment]
Ah, gotcha. I'll check out the latest and greatest.

**Comment by monfresh** [comment]
Similarly, the validator is complaining that status is missing:

```
The property '#/' did not contain a required property of 'status' in schema 7df96eff-9999-5f32-8a24-b763d765e573#
```

**Comment by arowla** [comment]
The `status` issue has been fixed in the code, but I'm not sure if @mbland
has cut a new version of the Gem yet. @mbland?

On Thu, Oct 29, 2015 at 12:59 PM, Moncef Belyamani <notifications@github.com

> wrote:
> 
> Similarly, the validator is complaining that status is missing:
> 
> The property '#/' did not contain a required property of 'status' in schema 7df96eff-9999-5f32-8a24-b763d765e573#
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/about_yml/issues/21#issuecomment-152248721.

## 

Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by mbland** [comment]
I have, and it's deployed to team-api.18f.gov, but @monfresh, what project is producing that error? I'm imagining it's showing up only because that particular `.about.yml` hasn't been updated since the new gem was pushed.

**Comment by arowla** [comment]
It's still showing 0.0.4, which is the version with the bug.

**Comment by mbland** [comment]
Whoops, you're right... I was thinking just of #18, not of #28.

**Comment by mtorres253** [comment]
Moving to done as #28 is resolved.
