### ISSUE TITLE
`testable` description should be tweaked

### ISSUE THREAD

**Issue by arowla** [18F/about_yml#24]
I think this description should be changed to:

```
Should be `true` if the project has automated tests
```

Currently it says "if the project has a continuous build", which I think is misleading, given the original intent of this field to be able to find testable repositories which needed to have continuous builds set up for them.

I'l send a PR in a moment.

**Comment by monfresh** [comment]
I think it should be even more generic than that. Some repos that are/should be testable might not yet have automated tests. So, the question is, "should this repo have automated tests?", or "is this a repo to which automated tests can be added?"

**Comment by arowla** [comment]
That's a great suggestion. I will update my PR.

**Comment by mbland** [comment]
Closed by #25.
