### ISSUE TITLE
Update contributing.md with pull request process

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#36]
As a contributor who is submitting pull requests, in order for me to feel like my contribution is being considered, and so that I am encouraged to continue contributing, I should know what to expect in terms of process, and who to contact if I want to follow up.

Acceptance criteria: There should be some documentation on how pull requests get handled and who to contact for follow-up. This documentation should be in a place in the repo where contributors will know to look for it. This documentation should live in 
https://github.com/18F/team-api.18f.gov
https://github.com/18F/about_yml
https://github.com/18F/team_api

Notes: Suggestion from dashboard team in 11/9/15 demo meeting.

**Comment by mtorres253** [comment]
@ccostino is getting together with the devs to go over the process. Once we decide on this process, documentation can be updated.

**Comment by mtorres253** [comment]
Depends on #41

**Comment by ccostino** [comment]
I'll have to submit separate pull requests for the other two CONTRIBUTING.md files since they're in different repositories.

Let's make sure the content of this change is good to go first, then I'll update the other two!

**Comment by ccostino** [comment]
I'm re-opening this issue briefly to account for a minor update to the file after seeing how closing issues worked in conjunction with the Waffle board.
