### ISSUE TITLE
notify owner if about.yaml fails to parse

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#37]
Project owners should know right away if there is a problem with their about.yml file. So, whenever one is created or updated, there should be some feedback (successful or unsuccessful)

Acceptance Criteria:
If I create or edit an about.yml file for my project,
And there is an error
I should get some kind of notification so that I can fix it.

Notes:
Leaving implementation open for now. Suggestion for error notification is that a pull request (and associated notification) is created when errors are found when the about.yml file is processed for Team API. OR Sarah has detailed another solution which is more immediate on create or update and involves feedback for success and error. Another solution is to add the unit test to the project somehow either by copy/paste or via a gem. 

Let's start with the unit test approach. We can add more functionality later if needed.

**Comment by mtorres253** [comment]
@mbland let's fill in the details of this one and prioritize. I'll set up another grooming meeting

**Comment by ultrasaurus** [comment]
I was thinking it would work like this:
- someone does a PR with an about.yml file
- there's an automated CI check for errors
- github UI shows if it passes
- team API adds a comment with a preview link to the PR so product manager can review what it looks like

cc @gboone

**Comment by mtorres253** [comment]
Thanks @ultrasaurus! I've updated the story to be a bit more clear on the user/value. We can go over implementation when we talk with the team.

**Comment by ertzeid** [comment]
How easy would it be to provide a simple unit test that would just parse the .about.yml file and fail if it's malformed? Then it could probably fit into most-to-all projects' established workflows, as well as show up in GitHub UI.

**Comment by mbland** [comment]
Pretty easy. Probably something like:

``` ruby
require 'about_yml'

about_file = File.join '../.about.yml'
about_data = SafeYAML.load_file about_file, safe: true
errors = ::AboutYml::AboutFile.validate_single_file about_data
unless errors.nil?
  $stderr.puts errors
  exit 1
end
```

Can write a generator for it, or just tell folks to cut 'n paste this as `test/about_yml_test.rb`.

**Comment by mbland** [comment]
Err, `require 'safe_yaml'` too.

**Comment by arowla** [comment]
I wonder if a unit test could somehow be included as part of the about_yml gem?

There's also, which is exactly what they need minus the fake data part. https://github.com/18F/about_yml/blob/master/spec/integration_spec.rb

**Comment by mtorres253** [comment]
Let's go over the existing unit test functionality that @mbland implemented. Maybe it's as simple as verifying that that will work as a bridge to a more comprehensive solution

**Comment by mbland** [comment]
Asked to re-prioritize this by the Dashboard team. Wonder if we can use the [Travis API](https://docs.travis-ci.com/api) to log an error from 18F/team-api-server when errors are detected, so that offending PRs can receive notifications.

cc: @DavidEBest

**Comment by ertzeid** [comment]
The goal of this change is to add tools that project owners can add that
check their `.about.yml` files and can be added to their own pre-commit
checks in GitHub, etc. That part can still happen without the Travis API,
no?

**Comment by mbland** [comment]
Perhaps, but Travis failures are the first thing we thought of.

**Comment by mtorres253** [comment]
Can this be moved over to the "Done" column? looks like the pull request was merged. Would love to see this in the demo on Friday

**Comment by ertzeid** [comment]
So this enables it, but I'd like to add something to the Hub repo that
provides an example of how users can enable the test themselves.

**Comment by ultrasaurus** [comment]
@ertzeid we had talked about doing a validation that didn't require set up for every repo.  With this as a standard for every repo and the ability to create org-wide commit hooks, seems like it would be a significant timesaver to look for commits about about.yml files in them, run the validator and report errors with a message on the commit or something like that.

@mtorres253 people tend look for technical docs in github rather than Hub.  I think it would make sense to consolidate about.yml docs in team-api repo and reference from dashboard.

**Comment by mbland** [comment]
As an MVP, we'll document how to integrate this current mechanism into a project so that validation will be performed as part of a Travis build. We'll open another story for a separate, standalone service integration as part of the 18F/team-api-server (which is already listening to an org-wide webhook to import/validate/build `.about.yml` updates).

**Comment by ertzeid** [comment]
PR for last bit of code for MVP (there will still be some documentation): https://github.com/18F/hub/pull/503
