### ISSUE TITLE
User research for project stages

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#38]
So that our users can store meaningful information about the stages of their projects, we should do further research to determine the following:
1. Definitions of alpha and beta
2. Uses of alpha and beta stages

Acceptance criteria: Competed interviews for the projects mentioned below

**Comment by mtorres253** [comment]
Questions are here: (https://docs.google.com/document/d/1BfrjDoHQWx2hVW1Lu_09hlbiq7cIwU3B92dbaIyLm-U/edit

Michael will interview:
- [x] 18F Site: https://docs.google.com/a/gsa.gov/document/d/1VuyWO1oyOqjXptLEgriiJMRvZLZw3VTtNRAuFjZYrEk/edit?usp=sharing
- [x] FEC
  https://docs.google.com/a/gsa.gov/document/d/10rfnv95k66NWg440PULnm1N2CXYuFudFJFB9l2ul2YU/edit?usp=sharing
- [x] Web Design Standards
  https://docs.google.com/a/gsa.gov/document/d/1eimcQvyyHPFGmGpx19MIF4ZKyVjKnCoM4J2YkUn4g_Y/edit?usp=sharing

Melody will interview:
- [x] Discovery/OASIS https://docs.google.com/document/d/1AfeIArTutZhxV-lK9QWKaSitblaJn8J8LL54p8xJuBo/edit
- [x] Peace Corps https://docs.google.com/document/d/16HgMC3CoU5lxie01D6d0wc-tXTwcn84MSH2cA-fbIeA/edit
- [x] Treasury https://docs.google.com/document/d/1j2JHttNC0JMOTvKFgma0K5wSagp6kiZE-Fjg3ljjdQk/edit

Let's add EITI - Michelle Hertzfeld

**Comment by melodykramer** [comment]
Interviews all set up for Monday.

**Comment by melodykramer** [comment]
@mtorres253 I finished all three interviews. Something very interesting jumped out. On all of these projects, ownership has been passed off to a vendor or agency. I'm not sure we account for that in question 2. The answer may vary, depending on the project - and I think we need to supply help text and remind people to update this answer when passing off ownership.

**Comment by melodykramer** [comment]
Also the people were able to describe stages much better when they were asked to not use the words alpha and beta.
