### ISSUE TITLE
Remove 'status' from schema

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#44]
As a consumer of Team API, and anyone who is trying to create or update a project in data-private, I should only see reference to fields that are actually being used. The 'status' field is not being used and therefore I should not see it.

Acceptance criteria:
I am a project owner and I am creating or updating data-private or the about.yml for my project
I do not see "Status" referenced in the schema for data-private
If I am reviewing about.yml documentation, I don't see a reference to "Status"
I am a consumer of Team API and I make a request for project data
I do not see 'status' returned by Team API

Notes:
We just need to delete from the schema and update documentation. Nothing else is needed.

**Comment by mtorres253** [comment]
The Team API bit of this may be a separate story for Team API. Let's just discuss how to handle these things in the future.

**Comment by ccostino** [comment]
It looks like this work should be done in https://github.com/18F/data-private/, no?  Specifically, removing from the schema here: https://github.com/18F/data-private/blob/master/schema.yml#L161?  Also, updating https://github.com/18F/data-private/blob/master/projects/README.md by removing the last line?

If so, I am going to close this issue and create a duplicate one over in `data-private`.

**Comment by ccostino** [comment]
Answered my own question while viewing the spreadsheet with the differences between `data-private` and `about.yml` schemas; closing this issue in favor of one on the correct repo.
