### ISSUE TITLE
migrate 'blog' in about.yml schema to 'links'

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#46]
To prepare for standardizing the schema, we should make sure that there are no conflicts between data-private and about.yml. Right now the attribute "blog" means different things. The data-private value is currently used by the dashboard to create a link to the 18F blog posts related to the project. The about.yml blog attribute is not currently used.

Acceptance criteria: The blog attribute in the about.yml schema means the same thing as the blog attribute in data-private.  'blog' changes to 'blog_tag'
- [x] migrate all existing blog values in about.yml to the links section. URI for blog becomes url: and text:, category is "blog"
- [x] blog attribute in about.yml means the same as it does in data-private. Rename to be clearer that this is a link to 18F blog entries for that project - 'blogTag'
- [x] coordinate with @gboone so that dashboard is not affected by this change

**Comment by mtorres253** [comment]
@gboone: Let's talk about a better name for the current "blog" attribute, one that communicates better what it's being used for

**Comment by gboone** [comment]
I'm into it.

**Comment by mtorres253** [comment]
@ertzeid Just verified that there is no need for the data migration in the first task. Marked it as complete.

**Comment by ertzeid** [comment]
Thanks!

**Comment by mtorres253** [comment]
@ertzeid I checked with our two .about.yml users and they see no issues with deprecating "blog" and moving to "blog_tag". @ultrasaurus mentioned that there may be a better format: "or “blogTag” if you end up following the version recommendation from WH/OMB that gray dug up". I have no preference but wanted to run by you and @mbland in case I'm missing something. We just need to coordinate with @gboone so that the dashboard expects blog_tag instead of blog.

**Comment by mtorres253** [comment]
Related issue in dashboard https://github.com/18F/dashboard/issues/310
