### ISSUE TITLE
Standardize schemas in _data and about.yml

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#47]
So that project owners and project leads can maintain accurate data for their projects, they should be clear that the schema in data-private is the same as the schema in about.yml, 

Acceptance criteria: 
- [ ] Once we get everything merged into the repo, the about.yml validator schema works for both the data-private directory and about.yml files in their own repos.

https://docs.google.com/a/gsa.gov/spreadsheets/d/1fumCEQ6IbsqX3mBfExYI63x0JdpXIXoX029GeDold0s/edit?usp=sharing

**Comment by mtorres253** [comment]
Short term we have a readme file in data-private and about.yml documenting schema. Longer term is to have an endpoint to the schema itself

**Comment by ccostino** [comment]
Are we referring to this schema for standardization?

https://github.com/18F/about-yml-validator/blob/master/lib/schema.json

**Comment by mbland** [comment]
@ccostino Yes. And per 18F/team-api.18f.gov#157 it's worth noting that 18F/data-private _may_ get folded into the `_data/` and/or `_data/private/` directory of 18F/team-api.18f.gov eventually.

**Comment by ccostino** [comment]
Gotcha, thanks @mbland!
