### ISSUE TITLE
Write instructions on how to complete fields in .about.yml

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#59]
In order for project leads to know how to enter data for the various .about.yml attributes, there should be instructions. In our roadmap discussion today, we thought it might be nice for us to prepare something more editorial directed to project leads.

Some things to consider:
1. How to set up an .about.yml for your project
2. How the .about.yml gets consumed by Team API and the dashboard (when it gets picked up, when it gets published to the dashboard, etc) -- this section should also mention that the project needs to get added to the comms whitelist for the dash
3. What each of the fields are for
4. How to enter data - when to use '', how to create new lines in paragraphs, how to create a mailto:link for contact email addresses, etc. 

We should store it somewhere in the about.yml repo so that we can update it easily when we change the schema

Cross-reference #39

Would like to pair with @andrewmaier on this one

**Comment by JJediny** [comment]
See comment on #53 which would address this via description field in the json schema

**Comment by mtorres253** [comment]
This is a duplicate of #181. Closing for now
