### ISSUE TITLE
Produce /schema endpoint for about.yml

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#68]
So that developers building tools that reference the about.yml schema have a canonical resource they can reference, we should create an endpoint for them to use.

**Comment by ccostino** [comment]
@mtorres253 and @mbland:  This issue should be in the https://github.com/18F/team-api.18f.gov/ repo instead, right?

**Comment by mbland** [comment]
@ccostino 18F/team_api#44

**Comment by ccostino** [comment]
Ah whoops, getting my repos mixed up!

**Comment by mtorres253** [comment]
Sorry, I'm going to close this issue and move 18F/team_api#44 to ready.
