### ISSUE TITLE
Stage and status

### ISSUE THREAD

**Issue by jeremiak** [18F/about_yml#8]
I'm not quite sure I completely understand the difference between these two nor if they capture all possible project states between the two.

For instance, the last stage possible is listed as `live` though we definitely have projects that were once live and might be shelved now. Would those projects have `stage` set to `live` and `status` set to deprecated? What if the project is not deprecated but the "live" version was just taken down for a different reason?

I also know that @jtag had some ideas about how to expand these two notions to make sure we can accurately capture the work that consulting does.

I propose adding another stage to the end called `sunset` that would be a stage after `live`.

cc @gboone @mbland @melodykramer

**Comment by mbland** [comment]
`status` was what was in the original `project.yml` file before I joined, and its only valid value was `Hold`, meaning it shouldn't show up on https://18f.gsa.gov/dashboard/. It's like an appendix; its function has been subsumed by the public/private filtering of the Hub/Team API, and it can go away.

`stage` seems to provide some continued utility. `sunset` sounds like a viable possibility, and there's probably room for other values too, per Consulting's ideas. We'd just need to coordinate with @gboone to reflect the status in the Dashboard accordingly.

**Comment by gboone** [comment]
Statuses/stages in the Dashboard definitely need a lot of work. Chiefly, I don't think the definitions we're using right now accurately reflect the way we actually think about our products and our work. I like including `sunset` and maybe even `transfered` or `ended` as stages that come after `live` and would love to help figure out new definitions, terms, and how we convey them on the Dashboard.

**Comment by jeremiak** [comment]
Awesome, I'm going to add in the new stages and remove the "status" key.

**Comment by jeremiak** [comment]
So @ultrasaurus brought up a great point in the call this morning, which is that 'ATO' isn't one of our stages, though it is definitely a conceptual stage that we apply to all of our products and projects. Should we remove the "alpha", "beta" distinction and have "alpha" and "ATO" or does "Live" imply "ATO"? Or is "ATO" too jargon-y for anybody else to understand so it doesn't have much meaning?

**Comment by ultrasaurus** [comment]
@jeremiak ATO would likely be an annotation, rather than a stage.  Sometimes we can ATO very early, but sometimes it happens very late.  For example, we can test with federal employees with an ATO, but I believe we need an ATO to test with citizens.  

On the change in stages, I was thinking of having an open brainstorm around stages and naming of them before actually making a change.  I was thinking of some kind of card-sorting exercise where we put all of our projects on the board (or a representative sample) and try to sort them into meaningful buckets.

**Comment by mbland** [comment]
Closed by #18, but discussion of "stage" values to take place on November 3.
