### ISSUE TITLE
Investigate json-editor as a potential .about.yml creation tool

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#81]
To give reflexive practitioners an easy way to create and maintain their .about.yml files, there should be a usable form that takes input and converts it into properly formatted yaml.

Acceptance criteria
Let's timebox to less than 4 hours and investigate whether json-editor can do this for us. We just want a form that takes input and generates a properly formatted .about.yml file. We don't need to do any validation at this point. That can come later.

**Comment by DavidEBest** [comment]
https://github.com/18F/about-yml-editor should satisfy the requirements for this. It seems that this solution should work, as long as @mtorres253 & @mbland are happy with the generated yaml.

**Comment by mtorres253** [comment]
Thanks @DavidEBest I'll move this to needs review
