### ISSUE TITLE
Partners

### ISSUE THREAD

**Issue by jeremiak** [18F/about_yml#9]
Right now we have a `partner` field that is to be an array of strings that represent "Partners for whom the project is developed". How can we capture people/orgs/groups that have either spun up an instance of a project and are using it and are perhaps even contributing things back to the project?

I think "Partners" makes sense for the current definition, how does the group feel about a field like "Implementers"? I think there's probably a better word to capture this group, but I just can't think of it.

@mbland @melodykramer @gboone

**Comment by jeremiak** [comment]
Tagging @jtag as well since I'm sure this has implications for consulting.

**Comment by mbland** [comment]
I think a `contributors` group would be good for people or organizations who've actively contributed to a project.

Perhaps a `users` group would be good to cover people/orgs that are actively using a product who aren't/haven't yet actually submitted contributions.

**Comment by gboone** [comment]
I think it'd be _awesome_ if we could highlight something like analytics.phila.gov, though. Is that what you're thinking here?

**Comment by melodykramer** [comment]
Yes exactly @gboone - that shows our impact and highlights the work of other groups.

**Comment by jeremiak** [comment]
@mbland I'm wondering if we even need `contributors`. My thought process is that it would be pretty annoying to have to update the `.about.yml` every time we accept a PR from a new contributor on Github. I'm wondering if we actually just want to list Github's contributors endpoint as a service instead so that any consumer can query that data and have it be up to date?

I think the problem with "users" is that users (to me) are the people who the actual product/project was developed for (in the sense of user-centered design).

What do you think of "forkers"? If that doesn't seem great to you, I'm just going to go with "Users" for now.

**Comment by mbland** [comment]
Closed by #17, though further discussion welcome in a new issue if needed.
